baseURL = "https://saahilclaypool.github.io/"
languageCode = "en-us"
publishDir = "docs"
canonifyurls = true

# Enable for syntax highlighting
pygmentsUseClasses = true
pygmentsCodefences = true

[markup.goldmark.renderer]
      unsafe = true

[params]
    description = "A collection of bits of knowledge"
    copyright= "Copyright © 2020 Saahil Claypool"
    Title = "Notes on things"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = ""
    url = "/this_site"
    weight = -140